### ISSUE TITLE
bug: URL encode markdown URLs

### ISSUE THREAD

**Issue by Zevoros-cyber** [philips/obsidian-plugin-supernote#12]
Here's the generated markdown which doesn't link to the note:

[Source Note](Supernote/Customer Implementation.note)
## Page 1

Customer Pre-Kick off
3/27/2024

It should be:

[[Supernote/Customer Implementation|Source Note]]
## Page 1

Customer Pre-Kick off
3/27/2024

**Comment by philips** [comment]
Gahh, TIL that you have to URL encode markdown links: https://help.obsidian.md/Linking+notes+and+files/Internal+links

**Comment by Zevoros-cyber** [comment]
@philips While the change to wikilink style works since it is supported by Obsidian and very easy to implement, TIL that some plug-ins specifically do not support Wikilink format for attachments as it is not standard markdown.  So, I hate to tell you this, but it would be best to use markdown URL type encoding for internal links to other files.

**Comment by philips** [comment]
Hrm, what plugins? Obsidian does say they use the Wikilinks by default:

By default, due to its more compact format, Obsidian generates links using the Wikilink format. If interoperability is important to you, you can disable Wikilinks and use Markdown links instead.

To use the Markdown format:

Open Settings.
Under Files & Links, disable Use [[Wikilink]].
Even if you disable the Wikilink format, you can still autocomplete links by typing two square brackets [[. When you select one of the suggested files, Obsidian instead generates a Markdown link.

**Comment by Zevoros-cyber** [comment]
Consistent Attachments and Links, for example.

**Comment by philips** [comment]
Ha ok. Will move back to the markdown links

**Comment by philips** [comment]
Ah, the API has the solution: https://docs.obsidian.md/Reference/TypeScript+API/FileManager/generateMarkdownLink
