### ISSUE TITLE
Feature Request: Option to grab *.note files from other locations on computer

### ISSUE THREAD

**Issue by freshminty** [philips/obsidian-plugin-supernote#7]
Heya! 
Would it be possible to add a feature to grab *.note files from outside the vault? I use Dropbox sync with my Supernote and would find it useful to grab the note files from the sync I am already using and place the image and md files into my vault. This would also likely require adding the last conversion and mod time monitoring into the plugin though if it's just currently checking if files placed into the vault are *.note, so it might be overly complex to add to what you have already.

Thanks!

**Comment by philips** [comment]
Can you just direct Dropbox to sync into a folder in your vault? 

I plan to add a regenerate tool. But, until then, you can just delete the files you want to have regenerated and restart Obsidian.

**Comment by dbmcco** [comment]
I love being able to see multi-page .notes in Obsidian, and I too would be happy to sync via Dropbox/Drive to a folder in my vault if, when I resync my Dropbox/drive, when I open the note in Obsidian, I get the most updated version. 

Is that what you mean by "regenerated"?

Also, realizing Markdown is not awesome when it comes to layout capabilities, what I would LOVE is being able to see a "Grid" of pages from a multi-page .note file with "side by side" viewing.   Such, that I could zoom in and out on them to get an overview of a series of notes.  Rather than a ever-down-scrolling set of pages.  

Love the potential of this - it's awesome.  Right now I am using the iFrame rendering link in Obsidian, and it's ok, but not really ideal.   To get at the use case above, I've added multiple of the same iframe URL to a canvas side by side.

**Comment by philips** [comment]
With the new v2 release (which I released yesterday) if you sync into a folder in your vault then everytime you open the note it will show the latest contents.

**Comment by philips** [comment]
I am going to close this because I don't want the plugin to attempt to walk around the filesystem out of the Vault for two reasons:

1. Getting the UX will be hard.
2. It won't work on mobile because it would rely on NodeJS APIs
